# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS macis::macis macis::lobpcgxx macis::sparsexx macis::spdlog)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target macis::macis
add_library(macis::macis SHARED IMPORTED)

set_target_properties(macis::macis PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/include;/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/tests/include"
  INTERFACE_LINK_LIBRARIES "MPI::MPI_CXX;OpenMP::OpenMP_CXX;Eigen3::Eigen;Boost::boost;macis::lobpcgxx;macis::sparsexx;macis::spdlog;std::mdspan"
)

# Create imported target macis::lobpcgxx
add_library(macis::lobpcgxx INTERFACE IMPORTED)

set_target_properties(macis::lobpcgxx PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/src/lobpcgxx/include"
  INTERFACE_LINK_LIBRARIES "blaspp;lapackpp"
)

# Create imported target macis::sparsexx
add_library(macis::sparsexx SHARED IMPORTED)

set_target_properties(macis::sparsexx PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_17"
  INTERFACE_INCLUDE_DIRECTORIES "/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/src/sparsexx/include;/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/tests/src/sparsexx/include"
  INTERFACE_LINK_LIBRARIES "MPI::MPI_CXX;OpenMP::OpenMP_CXX"
)

# Create imported target macis::spdlog
add_library(macis::spdlog SHARED IMPORTED)

set_target_properties(macis::spdlog PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SPDLOG_SHARED_LIB;FMT_SHARED;SPDLOG_COMPILED_LIB"
  INTERFACE_INCLUDE_DIRECTORIES "/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/tests/_deps/spdlog-src/include"
  INTERFACE_LINK_LIBRARIES "Threads::Threads"
)

# Import target "macis::macis" for configuration "Release"
set_property(TARGET macis::macis APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(macis::macis PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/tests/src/macis/libmacis.so"
  IMPORTED_SONAME_RELEASE "libmacis.so"
  )

# Import target "macis::sparsexx" for configuration "Release"
set_property(TARGET macis::sparsexx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(macis::sparsexx PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/tests/src/sparsexx/libsparsexx.so"
  IMPORTED_SONAME_RELEASE "libsparsexx.so"
  )

# Import target "macis::spdlog" for configuration "Release"
set_property(TARGET macis::spdlog APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(macis::spdlog PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/diego/Documents/SISSA/Projects/CI_solver/MACIS_build/tests/_deps/spdlog-build/libspdlog.so.1.12.0"
  IMPORTED_SONAME_RELEASE "libspdlog.so.1.12"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "std::mdspan" "blaspp" "lapackpp" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
